### ISSUE TITLE
ValueError: Error when checking : expected dense_Dense1_input to have shape [null,50] but got array with shape [1,8].

### ISSUE THREAD

**Issue by gianlucatursi** [ran-j/ChatBotNodeJS#11]
Hi, 

After cloning and installing all dependencies i start the project. 
After adding just one intent and build the agent i try the chat. After first message i got this error:

```
ValueError: Error when checking : expected dense_Dense1_input to have shape [null,50] but got array with shape [1,8].
```

**Comment by ran-j** [comment]
Hello, witch node version you are using and if possible what did you train

**Comment by gianlucatursi** [comment]
i'm using node v16.6 and i trained i simple question like "how are you"

**Comment by ran-j** [comment]
yes there is some kind of problem with latest node version. I will update this project and do some fix

**Comment by gianlucatursi** [comment]
> yes there is some kind of problem with latest node version. I will update this project and do some fix

With what version of node working ?

**Comment by ran-j** [comment]
In that time I used node 8 I guess

**Comment by ran-j** [comment]
Hmm looks like when you only have one intent the bot just give this error

**Comment by ran-j** [comment]
This should do the trick c9a29d4015002a70f3082ee151bb9b5f0705d7cb
