### ISSUE TITLE
can we extract entity ?

### ISSUE THREAD

**Issue by imReCoder** [ran-j/ChatBotNodeJS#14]
I want to extract entity from the setence

for example : order 23 cups

entity: 23
entityType : quantity

**Comment by ran-j** [comment]
you can give a try with https://github.com/spencermountain/compromise/

**Comment by ran-j** [comment]
![image](https://user-images.githubusercontent.com/17410205/182007985-a6442d8e-f4a2-4d04-8ad1-93ed7e6c724b.png)

 ok, I added this feature now ea7a3d1d2bec7afa447234fc66fe87e341ed0c6d
