### ISSUE TITLE
Broken :(

### ISSUE THREAD

**Issue by NotDemonix** [ran-j/ChatBotNodeJS#18]
I added intents and retrained model, it added intents to db but it still cant understand even with exact word

**Comment by ran-j** [comment]
after the training you can test in http://localhost:3007/

**Comment by ran-j** [comment]
please provide more info like whats is your node version and OS and logs

**Comment by ran-j** [comment]
ah ok, its really broken I will fix that

**Comment by ran-j** [comment]
try this new release 3e4568ff407fe74a8dfb5f82565f2eb068067310

**Comment by NotDemonix** [comment]
Thanks but i will most likely use diffrent one as it will be easier for me to integrate with discord

**Comment by ran-j** [comment]
I created a api router you will Just need tô created a interface for discord. But for a discord bot I dont think you will need a deep learning bot

**Comment by NotDemonix** [comment]
I need for chatbot, but i think yours will be better than the one i found as yours use mongodb instead of json and doesnt base on "welcome", "goodbye", "compliment", "insult"

**Comment by NotDemonix** [comment]
Btw, could you by any chance add some self learning method? (Like if guess accuracy is x or higher then it saves response)

**Comment by ran-j** [comment]
Self learning is a bit hard to implements but maybe in the future I can implement that

**Comment by NotDemonix** [comment]
> Self learning is a bit hard to implements but maybe in the future I can implement that

This guy https://github.com/GandyT/Learner/blob/master/Commands/lnr.js implemented this as just check how confident bot is (which you already know as i saw in code) and if its more than 60% then it saves it

**Comment by NotDemonix** [comment]
If you will add this i will use your code as it seems better

**Comment by NotDemonix** [comment]
Btw, 2 more things:
Do you have discord?
Why you save conversations into mongodb

**Comment by NotDemonix** [comment]
Welp i think it doesnt work on arm64?
https://media.discordapp.net/attachments/791761968439492658/1003729433309483098/IMG_20220801_202052.jpg?width=1080&height=459

**Comment by NotDemonix** [comment]
image

**Comment by ran-j** [comment]
my discord Ran-J#2274

**Comment by ran-j** [comment]
you need to create a envfile, this should be on readme

**Comment by NotDemonix** [comment]
Yes im stupid i forgot

**Comment by NotDemonix** [comment]
Huh, arm64 https://media.discordapp.net/attachments/791761968439492658/1003759665001279570/IMG_20220801_222108.jpg i cant get nodejs to update on sudo so i cant use sudo cuz it still have nodejs 12

**Comment by NotDemonix** [comment]
I checked and napi-v8 doesnt exist in tensorflow folder, i think i need to build tensorflow lite
