### ISSUE TITLE
Not Able to Run It, Failing at start, please help

### ISSUE THREAD

**Issue by Deitek** [ran-j/ChatBotNodeJS#3]
Hi, I'm following the instructions provided, but I'm not able to run it ,

**Instructions followed:**
     $ npm install
     $ npm start

**This is the issue that is showing me at the Terminal**
> chatbottensorflow@2.3.1 start C:\Users\edalh\Downloads\ChatBotNodeJS-master(1)\ChatBotNodeJS-master
> node ./bin/www

internal/modules/cjs/loader.js:1003
  return process.dlopen(module, path.toNamespacedPath(filename));
....
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chatbottensorflow@2.3.1 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chatbottensorflow@2.3.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**This is a Log Extract**
10 silly lifecycle chatbottensorflow@2.3.1 ~start: Args: [ '/d /s /c', 'node ./bin/www' ]
11 silly lifecycle chatbottensorflow@2.3.1 ~start: Returned: code: 1  signal: null
12 info lifecycle chatbottensorflow@2.3.1 ~start: Failed to exec start script
13 verbose stack Error: chatbottensorflow@2.3.1 start: `node ./bin/www`
13 verbose stack Exit status 1

**And in Order to solved I did the following:**

- Step 1: $ npm cache clean --force

- Step 2: Delete node_modules by $ rm -rf node_modules folder or delete it manually by going into the directory and right-click > delete / move to trash. Also, delete package-lock.json file too.

- Step 3: npm install

- To start again, $ npm start

But didn't solve the issue,

Please your help, I think your code can help me with a project assignment, that I need to delivery

thanks,

kind regards,

Deitek

**Comment by ran-j** [comment]
![image](https://user-images.githubusercontent.com/17410205/68259903-ef77a700-0019-11ea-848c-4fc8e2dbab01.png)
I download the project in a different machine and works normally.

Try run directly by going to folder "bin" and then run "node www".

Sorry for late response.

**Comment by ran-j** [comment]
I add a docker setup, try it, I can't test right now

**Comment by Deitek** [comment]
It didn't work. I think your machine is something related to the path, differences because your machine seems is Linux, and I work in a windows machine (check the following)

internal/modules/cjs/loader.js:1003
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\ChatBotNodeJS-master\node_modules\@tensorflow\tfjs-node\lib\napi-v4\tfjs_binding.node

**Comment by ran-j** [comment]
My machine is Windows 10 and this seens to be a error with your tensorflow instalation.

As I said use docker to run the project

**Comment by ran-j** [comment]
Good look
