### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by orcema** [ran-j/ChatBotNodeJS#9]
**Describe the bug**
followed install instructions in readme but i get this error:
> chatbottensorflow@2.7.2 start /usr/src/javascript/ChatBotNodeJS
> node ./bin/www

Illegal instruction
npm ERR! code ELIFECYCLE
npm ERR! errno 132
npm ERR! chatbottensorflow@2.7.2 start: `node ./bin/www`
npm ERR! Exit status 132
npm ERR! 
npm ERR! Failed at the chatbottensorflow@2.7.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**To Reproduce**
follow instructions in readme

**Expected behavior**
should start

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS, Linux (Ryzen)
 - Browser chrome

**Comment by ran-j** [comment]
Ops sorry for later response but you can try 

```
npm cache clean --force.
delete node_modules folder.
delete package-lock. json file.
npm install.
```

**Comment by ran-j** [comment]
also try docker https://github.com/ran-j/ChatBotNodeJS#use-respository

**Comment by ran-j** [comment]
Also try this new version c9a29d4015002a70f3082ee151bb9b5f0705d7cb
